on:
  - push
  - workflow_dispatch

jobs:
  wpscan:
    runs-on: ubuntu-latest
    name: WPScan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan
        uses: ./
        id: wpscan
        with:
          url: 'https://www.shanghaimansion.com/'
#          token: ${{ secrets.WPSCAN_TOKEN }}
          webhook: ${{ secrets.SLACK_WEBHOOK }}
      - name: Results
        run: |
          echo "${{ steps.wpscan.outputs.resultb64 }}"